abstract class AppStrings {
  static const mandopy = "مندوبي",
      creatNewAccount = "انشاء حساب جديد !",
      welcom = "مرحبا بك  ",
      signIn = "تسجيل الدخول",
      donotHaveAnAccount = "ليس لديك حساب ؟ ",
      resendCode = "إعادة إرسال الرمز",
      creatAcount = "انشئ حساب",
      hintName = "ادخل اسمك ثلاثي",
      emailHint = " ادخل البريد الالكتروني",
      hintPassword = "ادخل كلمة المرور",
      hintConfirmPassword = "ادخل كلمة المرور مرة اخري",
      confirmOtp = "تأكيد كود التسجيل",
      otpMessage = "يرجى التحقق من بريدك الإلكتروني للحصول على رمز التحقق",
      email = "البريد الالكتروني",
      forgetPasswordMessage =
          'أدخل حساب بريدك الإلكتروني لإعادة تعيين كلمة المرور الخاصة بك.',
      name = "الاسم",
      password = "كلمة المرور",
      newPassword = "كلمة المرور الجديدة",
      confirmNewPassword = "تأكيد كلمة المرور الجديدة",
      resetPassword = "إعادة تعيين كلمة المرور",
      confirm = "تأكيد",
      send = "ارسال",
      confirmPassword = "تأكيد كلمة المرور",
      forgetPassword = "هل نسيت كلمة المرور ؟",
      confirmationCode = "كود التسجيل",
      typeOfRepersentative = "نوع المندوب",
      scienstific = "علمي",
      sales = "تجاري",
      creatAccount = "انشئ حساب",
      haveAnAccoun = "لديك حساب بالفعل ؟ ",
      signInNow = "تسجيل الدخول ",
      hintConfirmationCode = "ادخل كود التسجيل الخاص بك";
}
